#!/bin/bash

#Check if we're root.
rT() {
       if [ "$(whoami)" != "root" ]
       then
           echo "You need to login as root to use this script! Sorry!";
           exit 1
       fi
}

#Checking OS.
OS() {
       if [ "$(grep DISTRIB_CODENAME /etc/*-release | awk -F '=' '{print $2}')" != "trusty" ]
       then
           echo "Seems like your system isn't Ubuntu 14.04!"
           echo "If so we can't start!"
           exit 1
       fi
}

setup() {
       apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y
       apt-get install build-essential bc systemd-services lshw libssl-dev wget ruby git nano curl zip unzip python -y
       apt-get autoremove -y
       apt-get install mysql-server mysql-client -y
       mkdir -p /opt/
       rm -Rf /tmp; mkdir -p /tmp; chmod -R 7777 /tmp
       cd ~
       wget http://cdn.systemroot.co/ex/downloads/iptv_panel_pro.zip -O /tmp/iptv_panel_pro.zip
       wget http://cdn.systemroot.co/ex/downloads/install_iptv_pro.zip && unzip install_iptv_pro.zip; rm -Rf install_iptv_pro.zip
       php install_iptv_pro.php
       cd /home/xtreamcodes/iptv_xtream_codes/nginx/conf/; rm -Rf nginx.conf
       wget https://raw.githubusercontent.com/systemroot/xtream-iptv-autoinstall/master/extra/nginx.conf
       killall nginx
       cd /home/xtreamcodes/iptv_xtream_codes/nginx/sbin/
       ./nginx
       sudo update-rc.d -f apache2 remove
       sudo update-rc.d apache2 disable
}

if [ "$1" == 'INSTALL' ]; then
        rT; OS; setup;
   else
        echo "Dear Mr. IDIOT."
        echo "Please Use The Fucking Command As iT iS On Github.!"
        echo "Bye."
fi
